@API_HostAddress = https://localhost:7110

GET {{API_HostAddress}}/v1/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/1
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/2
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/0
Accept: application/json