@API_HostAddress = https://localhost:7110

GET {{API_HostAddress}}/v1/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/1
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/2
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/0
Accept: application/json


###

GET {{API_HostAddress}}/v1/items
Accept: application/json


###

POST {{API_HostAddress}}/v1/items
Content-Type: application/json

{
  "Name": "Green Staff 3",
  "Description": "Is green?"
}

###

POST {{API_HostAddress}}/v1/items
Content-Type: application/json

{
  "Name": "New Item!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "Description": "This is a new item"
}

###

DELETE {{API_HostAddress}}/v1/items/13

###