@API_HostAddress = https://localhost:7110
//@Token =

GET {{API_HostAddress}}/v1/weatherforecast/
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/1
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/2
Accept: application/json

###

GET {{API_HostAddress}}/v1/items/0
Accept: application/json

###

GET {{API_HostAddress}}/v1/items
Accept: application/json

###

POST {{API_HostAddress}}/v1/items
Content-Type: application/json

{
  "Name": "Green Staff 7",
  "Description": "Is green?"
}

###

POST {{API_HostAddress}}/v1/items
Content-Type: application/json

{
  "Name": "New Item!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "Description": ""
}

###

POST {{API_HostAddress}}/v1/items
Content-Type: application/json

{
  "Name": "             ",
  "Description": "    "
}

###

PATCH {{API_HostAddress}}/v1/items/4
Content-Type: application/json

{
  "Name": "Updated Item Name xddd",
  "Description": "This is an updated description"
}

###

PATCH {{API_HostAddress}}/v1/items/99999
Content-Type: application/json

{
  "Name": "Updated Item Name",
  "Description": "This is an updated description"
}

###

DELETE {{API_HostAddress}}/v1/items/14

###

POST {{API_HostAddress}}/v1/identity/register
Content-Type: application/json

{
  "UserName": "author4",
  "UserEmail": "author4@test.com",
  "Password": "Password1!"
}

###

POST {{API_HostAddress}}/v1/identity/register
Content-Type: application/json

{
  "UserName": "",
  "UserEmail": "",
  "Password": ""
}

###

POST {{API_HostAddress}}/v1/identity/login
Content-Type: application/json
X-Client-Type: Browser

{
    "userName": "author3",
    "Password": "Password1!"
}

### 

POST {{API_HostAddress}}/v1/users/0199ecd7-ff74-7e95-95b5-539c4f54d23b/roles
Content-Type: application/json

{
  "RoleName": "User"
}

### 

POST {{API_HostAddress}}/v1/users/0199ecd7-ff74-7e95-95b5-539c4f54d23b/roles
Content-Type: application/json

{
  "RoleName": "Admineek"
}








